### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/config-specs#2]
1. Use `release-drafter/release-drafter@v5` to generate release notes and create release drafts on merged PRs.
2. Listen on new releases and do npm publish something like:

```
      - uses: actions/checkout@v2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn install
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
```
